on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_CHANNEL: sampler
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Run Results for your reference :rocket:'
        SLACK_TITLE: QA Automation Test Results
        SLACK_USERNAME: QABot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
